exports.CONFIG = {
	INFISICAL_HOST: process.env.INFISICAL_HOST,
	INFISICAL_CLIENT_ID: process.env.INFISICAL_CLIENT_ID,
	INFISICAL_CLIENT_SECRET: process.env.INFISICAL_CLIENT_SECRET,
	INFISICAL_PROJECT_ID: process.env.INFISICAL_PROJECT_ID,
	APP_FOLDERS: process.env.APP_FOLDERS.split(","),
	ENV_TYPES: process.env.ENV_TYPES.split(","),
};
